// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAikFJ7z6mhc6qKUZ_rbdvwB0P7yCgKky8',
    appId: '1:796571505402:web:0a2085b683aa7c841fef43',
    messagingSenderId: '796571505402',
    projectId: 'campusloop-9c692',
    authDomain: 'campusloop-9c692.firebaseapp.com',
    storageBucket: 'campusloop-9c692.firebasestorage.app',
    measurementId: 'G-TYZQZ0W7HD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmF6cGHs0vKR6OizWkTc75qqRqfk1SB48',
    appId: '1:796571505402:android:ee49ab776024d4f61fef43',
    messagingSenderId: '796571505402',
    projectId: 'campusloop-9c692',
    storageBucket: 'campusloop-9c692.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT96_X2DbglT5IospHpXSkyCWePJ5qG84',
    appId: '1:796571505402:ios:90cc6316ef21e8341fef43',
    messagingSenderId: '796571505402',
    projectId: 'campusloop-9c692',
    storageBucket: 'campusloop-9c692.firebasestorage.app',
    iosBundleId: 'com.example.campusloop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT96_X2DbglT5IospHpXSkyCWePJ5qG84',
    appId: '1:796571505402:ios:90cc6316ef21e8341fef43',
    messagingSenderId: '796571505402',
    projectId: 'campusloop-9c692',
    storageBucket: 'campusloop-9c692.firebasestorage.app',
    iosBundleId: 'com.example.campusloop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAikFJ7z6mhc6qKUZ_rbdvwB0P7yCgKky8',
    appId: '1:796571505402:web:2f9917b840d069931fef43',
    messagingSenderId: '796571505402',
    projectId: 'campusloop-9c692',
    authDomain: 'campusloop-9c692.firebaseapp.com',
    storageBucket: 'campusloop-9c692.firebasestorage.app',
    measurementId: 'G-8K60PSGST0',
  );
}
